-- The ledger, as originally written.
CREATE TABLE IF NOT EXISTS ledger (
   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_last4      VARCHAR(4)     NOT NULL,
    occurred_at        VARCHAR(40)    NOT NULL,
    direction          VARCHAR(6)     NOT NULL,
    amount             DECIMAL(14, 2) NOT NULL,
    category           VARCHAR(10)    NOT NULL,
    merchant           VARCHAR(120),
    source_message_ids VARCHAR(500)   NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_ledger_account ON ledger (account_last4);
